### ISSUE TITLE
Extract not working properly ?

### ISSUE THREAD

**Issue by emondpph** [Nothing-Works/vuetifyjs-mix-extension#16] opened 2020-10-16 03:02 UTC
Hi,

Thanks for your work. I managed to make everything work. The only problem left is the extract functionnality for the Vuetify CSS. It does export but not at the right place.

<pre>
`mix.js('vue/app.js', 'public/js/app-vue.js');  
mix.vuetify('vuetify-loader', 'css/app/_vuetify.scss', {
    extract: 'public/css/app-vuetify.css',
});`
</pre>
When I run with npm run watch, the extracted CSS file goes to (according to console):
public/css//public/js/app-vue.app-vuetify.css

What am I doing wrong ?
Thanks !

**Comment by Nothing-Works** [comment] 2020-10-17 06:24
@emondpph The library does not do anything special about the path, it just passes the path to the `MiniCssExtractPlugin`  webpack plugin. Because by default `laravel-mix` output is the public directory so if you just do 'css/vuetify-components.css' it should be the right place.

**Comment by Nothing-Works** [comment] 2020-10-18 07:54
Will close this, for now, feel free to discuss if you have any questions.

**Comment by emondpph** [comment] 2020-10-19 14:38
Hi thanks for your comment. I am using Laravel Mix (stand-alone) without Laravel. I don't know if this could be part of the issue... If you don't mind I just copy-paste my full webpack.mix.js file. If you see something that could cause this conflict, please advise. Otherwise thanks for your help and work.

At the moment, I changed the extract path to 'app-vuetify.css'. And it gets exported to:
**/public/js/app-vendor.app-vuetify.css**.
Something funky happening with the paths, it kind of just gets appended to the other extracted JS file.

Here is:
`const mix = require('laravel-mix');
require('vuetifyjs-mix-extension');

mix.options({
    extractVueStyles: 'public/css/app-vue.css',
    globalVueStyles: 'css/app/vue.scss',
});
mix.sass('css/app/app.scss', 'public/css/app.css');
mix.js('vue/app.js', 'public/js/app-vue.js');
mix.vuetify('vuetify-loader', 'css/app/vuetify.scss', {
    extract: 'app-vuetify.css',
});
mix.extract(['vue', 'vuex', 'vuetify'], 'public/js/app-vendor.js');
mix.sourceMaps();
mix.browserSync({
    proxy: 'https://udeclic.test',
    files: ['lemur/**/*.php', 'css/**/*.scss', 'vue/**/*.vue', 'vue/**/*.js'],
});
`

**Comment by Nothing-Works** [comment] 2020-10-21 02:54
This seems like a bug, the problem is when you use `extract`, `laravel-mix` auto set the chunk name from the second argument of the `extract` method. And `MiniCssExtractPlugin` will also use it as the chunk so you had the weird path problem. I think I can have a quick fix.

**Comment by Nothing-Works** [comment] 2020-10-21 09:25
The latest version which is `0.0.17` should fix this problem.

According to your setup, you can specify the full destination path like ` extract: 'public/css/app-vuetify.css',`

**Closed** 2020-10-21 09:27 UTC

**Comment by emondpph** [comment] 2020-10-21 14:21
Yeah you fixed it, great job thanks
